font_family JetBrainsmono Nerf Font
font_size 11.0
confirm_os_window_close 0
background_opacity 0.72
dynamic_background_opacity yes
background_blur 8
foreground #dfe7df
background #050805
cursor #00ff41
selection_background #173117
selection_foreground #ecf4ec
color2 #00FF41
color10 #7CFF7A
color8 #2A5A2A
color15 #D8FFD8
window_padding_width 10
enable_audio_bell no
visual_bell_duration 0.0
scrollbar never
cursor_shape beam
cursor_blink_interval 0.8
cursor_trail 12
cursor_trail_decay 0.1 0.35
cursor_trail_color #00ff41
active_border_color #44ff88
inactive_border_color #1c301c
